FROM golang:1.7.3-alpine

MAINTAINER TFG Co <backend@tfgco.com>

RUN mkdir /app
ADD ./bin/marathon-linux-amd64 /app
ADD ./config /app/config

WORKDIR /app

# BASIC AUTH
ENV MARATHON_BASICAUTH_USERNAME ""
ENV MARATHON_BASICAUTH_PASSWORD ""

# POSTGRES
ENV MARATHON_POSTGRES_HOST 0.0.0.0
ENV MARATHON_POSTGRES_PORT 5432
ENV MARATHON_POSTGRES_USER marathon
ENV MARATHON_POSTGRES_DBNAME marathon
ENV MARATHON_SENTRY_URL ""

# REDIS
ENV MARATHON_REDIS_HOST=localhost
ENV MARATHON_REDIS_PORT=9920
ENV MARATHON_REDIS_DB=0
ENV MARATHON_REDIS_PASSWORD=""
ENV MARATHON_REDIS_MAXPOOLSIZE=20

# S3
ENV MARATHON_S3_BUCKET="tfg-push-notifications"
ENV MARATHON_S3_FOLDER="test/files"
ENV MARATHON_S3_DAYSEXPIRY=1
ENV MARATHON_S3_ACCESSKEY="ACCESS-KEY"
ENV MARATHON_S3_SECRETACCESSKEY="SECRET-ACCESS-KEY"

# WORKERS
ENV MARATHON_WORKERS_LOGGER_LEVEL="debug"
# FIXME: WE HAVE TO KEEP THIS IN SYNC WITH AGUIA AND WE SHOULD NOT HAVE UNDERSCORES HERE
ENV MARATHON_WORKERS_CONSUMER_CONSUMERGROUPTEMPLATE="%s-%s-cg"
ENV MARATHON_WORKERS_PRODUCER_topicTemplate="%s-%s-p"
ENV MARATHON_WORKERS_CONSUMER_topicTemplate="%s-%s-c"
ENV MARATHON_WORKERS_CONSUMER_BROKERS='["localhost:9940"]'
ENV MARATHON_WORKERS_PRODUCER_BROKERS='["localhost:9940"]'
ENV MARATHON_WORKERS_MODULES_PRODUCERS=1
ENV MARATHON_WORKERS_MODULES_BATCHPGWORKERS=1
ENV MARATHON_WORKERS_MODULES_PARSERS=1
ENV MARATHON_WORKERS_MODULES_FETCHERS=1
ENV MARATHON_WORKERS_MODULES_BUILDERS=1
ENV MARATHON_WORKERS_MODULES_PRODUCERS=1
ENV MARATHON_WORKERS_MODULES_BATCHPGWORKERSTATUSDONECHAN=1
ENV MARATHON_WORKERS_MODULES_BATCHPGWORKERDONECHAN=1
ENV MARATHON_WORKERS_MODULES_PGTOPARSERCHAN=10000
ENV MARATHON_WORKERS_MODULES_PARSERDONECHAN=1
ENV MARATHON_WORKERS_MODULES_PARSERTOFETCHERCHAN=1000
ENV MARATHON_WORKERS_MODULES_FETCHERDONECHAN=1
ENV MARATHON_WORKERS_MODULES_FETCHERTOBUILDERCHAN=1000
ENV MARATHON_WORKERS_MODULES_BUILDERDONECHAN=1
ENV MARATHON_WORKERS_MODULES_BUILDERTOPRODUCERCHAN=1000
ENV MARATHON_WORKERS_MODULES_PRODUCERDONECHAN=1

EXPOSE 80

CMD /app/marathon-linux-amd64 start-server -p 80 -c /app/config/default.yaml
